config/routes.rb
Rails.application.routes.draw do

  resources :service_lines

  resources :tickets

  resources :services

  resources :vehicles

  resources :customers

  resources :ticket_statuses

  resources :service_statuses

  resources :categories

  resources :parts

  resources :employees

  Rails.application.routes.draw do

  devise_for :users
    get "/pages/:page" => "pages#show"
  end

  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :vehicles
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :service_lines
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_many :service_lines
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :service_lines
  belongs_to :category
end

app/models/service_line.rb
class ServiceLine < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :service
  belongs_to :service_status
  belongs_to :employee
  belongs_to :part
end

app/models/service_status.rb
class ServiceStatus < ActiveRecord::Base
  has_many :service_lines
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :ticket_status
  has_many :service_lines
end

app/models/ticket_status.rb
class TicketStatus < ActiveRecord::Base
  has_many :tickets
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :customer
  has_many :tickets
end

app/controllers/service_lines_controller.rb
class ServiceLinesController < ApplicationController
  before_action :set_service_line, only: [:show, :edit, :update, :destroy]

  # GET /service_lines
  # GET /service_lines.json
  def index
    @service_lines = ServiceLine.all
  end

  # GET /service_lines/1
  # GET /service_lines/1.json
  def show
  end

  # GET /service_lines/new
  def new
    @service_line = ServiceLine.new
  end

  # GET /service_lines/1/edit
  def edit
  end

  # POST /service_lines
  # POST /service_lines.json
  def create
    @service_line = ServiceLine.new(service_line_params)

    respond_to do |format|
      if @service_line.save
        format.html { redirect_to @service_line, notice: 'Service line was successfully created.' }
        format.json { render :show, status: :created, location: @service_line }
      else
        format.html { render :new }
        format.json { render json: @service_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_lines/1
  # PATCH/PUT /service_lines/1.json
  def update
    respond_to do |format|
      if @service_line.update(service_line_params)
        format.html { redirect_to @service_line, notice: 'Service line was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_line }
      else
        format.html { render :edit }
        format.json { render json: @service_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_lines/1
  # DELETE /service_lines/1.json
  def destroy
    @service_line.destroy
    respond_to do |format|
      format.html { redirect_to service_lines_url, notice: 'Service line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_line
      @service_line = ServiceLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_line_params
      params.require(:service_line).permit(:hour, :note, :Ticket_id, :Service_id, :ServiceStatus_id, :Employee_id, :Part_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/service_lines_helper.rb
module ServiceLinesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/service_lines/_form.html.erb
<%= form_for(@service_line) do |f| %>
  <% if @service_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_line.errors.count, "error") %> prohibited this service_line from being saved:</h2>

      <ul>
      <% @service_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hour %><br>
    <%= f.text_field :hour %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :Ticket_id %><br>
    <%= f.text_field :Ticket_id %>
  </div>
  <div class="field">
    <%= f.label :Service_id %><br>
    <%= f.text_field :Service_id %>
  </div>
  <div class="field">
    <%= f.label :ServiceStatus_id %><br>
    <%= f.text_field :ServiceStatus_id %>
  </div>
  <div class="field">
    <%= f.label :Employee_id %><br>
    <%= f.text_field :Employee_id %>
  </div>
  <div class="field">
    <%= f.label :Part_id %><br>
    <%= f.text_field :Part_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_lines/edit.html.erb
<h1>Editing service_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_line %> |
<%= link_to 'Back', service_lines_path %>

app/views/service_lines/index.html.erb
<h1>Service Lines</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Hour</th>
      <th>Note</th>
      <th>Ticket</th>
      <th>Service</th>
      <th>Servicestatus</th>
      <th>Employee</th>
      <th>Part</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_lines.each do |service_line| %>
      <tr>
        <td><%= service_line.hour %></td>
        <td><%= service_line.note %></td>
        <td><%= service_line.Ticket %></td>
        <td><%= service_line.Service %></td>
        <td><%= service_line.ServiceStatus %></td>
        <td><%= service_line.Employee %></td>
        <td><%= service_line.Part %></td>
        <td><%= link_to 'Show', service_line %></td>
        <td><%= link_to 'Edit', edit_service_line_path(service_line) %></td>
        <td><%= link_to 'Destroy', service_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service line', new_service_line_path %>

app/views/service_lines/new.html.erb
<h1>New service_line</h1>

<%= render 'form' %>

<%= link_to 'Back', service_lines_path %>

app/views/service_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hour:</strong>
  <%= @service_line.hour %>
</p>

<p>
  <strong>Note:</strong>
  <%= @service_line.note %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @service_line.Ticket %>
</p>

<p>
  <strong>Service:</strong>
  <%= @service_line.Service %>
</p>

<p>
  <strong>Servicestatus:</strong>
  <%= @service_line.ServiceStatus %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @service_line.Employee %>
</p>

<p>
  <strong>Part:</strong>
  <%= @service_line.Part %>
</p>

<%= link_to 'Edit', edit_service_line_path(@service_line) %> |
<%= link_to 'Back', service_lines_path %>