config/routes.rb
Rails.application.routes.draw do

  resources :service_lines

  resources :tickets

  resources :services

  resources :vehicles

  resources :customers

  resources :ticket_statuses

  resources :service_statuses

  resources :categories

  resources :parts

  resources :employees

  Rails.application.routes.draw do

  devise_for :users
    get "/pages/:page" => "pages#show"
  end

  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :vehicles
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :service_lines
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_many :service_lines
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :service_lines
  belongs_to :category
end

app/models/service_line.rb
class ServiceLine < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :service
  belongs_to :service_status
  belongs_to :employee
  belongs_to :part
end

app/models/service_status.rb
class ServiceStatus < ActiveRecord::Base
  has_many :service_lines
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :ticket_status
  has_many :service_lines
end

app/models/ticket_status.rb
class TicketStatus < ActiveRecord::Base
  has_many :tickets
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :customer
  has_many :tickets
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:year, :make, :model, :GVW, :license, :miles, :motor, :VIN, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :GVW %><br>
    <%= f.text_field :GVW %>
  </div>
  <div class="field">
    <%= f.label :license %><br>
    <%= f.text_field :license %>
  </div>
  <div class="field">
    <%= f.label :miles %><br>
    <%= f.text_field :miles %>
  </div>
  <div class="field">
    <%= f.label :motor %><br>
    <%= f.text_field :motor %>
  </div>
  <div class="field">
    <%= f.label :VIN %><br>
    <%= f.text_field :VIN %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Vehicles</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Year</th>
      <th>Make</th>
      <th>Model</th>
      <th>GVW</th>
      <th>License</th>
      <th>Miles</th>
      <th>Motor</th>
      <th>VIN</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.GVW %></td>
        <td><%= vehicle.license %></td>
        <td><%= vehicle.miles %></td>
        <td><%= vehicle.motor %></td>
        <td><%= vehicle.VIN %></td>
        <td><%= vehicle.customer %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Gvw:</strong>
  <%= @vehicle.GVW %>
</p>

<p>
  <strong>License:</strong>
  <%= @vehicle.license %>
</p>

<p>
  <strong>Miles:</strong>
  <%= @vehicle.miles %>
</p>

<p>
  <strong>Motor:</strong>
  <%= @vehicle.motor %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @vehicle.VIN %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @vehicle.customer %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>