config/routes.rb
Rails.application.routes.draw do

  resources :service_lines

  resources :tickets

  resources :services

  resources :vehicles

  resources :customers

  resources :ticket_statuses

  resources :service_statuses

  resources :categories

  resources :parts

  resources :employees

  Rails.application.routes.draw do

  devise_for :users
    get "/pages/:page" => "pages#show"
  end

  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :vehicles
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :service_lines
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_many :service_lines
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :service_lines
  belongs_to :category
end

app/models/service_line.rb
class ServiceLine < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :service
  belongs_to :service_status
  belongs_to :employee
  belongs_to :part
end

app/models/service_status.rb
class ServiceStatus < ActiveRecord::Base
  has_many :service_lines
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :ticket_status
  has_many :service_lines
end

app/models/ticket_status.rb
class TicketStatus < ActiveRecord::Base
  has_many :tickets
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :customer
  has_many :tickets
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>